---

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 43200   # 12 hours

- name: Install libcap
  ansible.builtin.apt:
    name: libcap2-bin
    state: present
  when: caddy_setcap
