---
- name: Converge
  hosts: all
  roles:
    - role: caddy-ansible
  tasks:
    - name: Ensure ss is installed (for testinfra)
      yum:
        name: iproute
        state: present
      when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']
