---
- name: Converge
  hosts: all
  roles:
    - role: caddy_ansible.caddy_ansible
      caddy_version: '2.7.6'
  tasks:
    - name: Ensure ss is installed (for testinfra)
      ansible.builtin.yum:
        name: iproute
        state: present
      when: ansible_distribution in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']
    - name: Ensure ss is installed (for testinfra)
      ansible.builtin.package:
        name: iproute2
        state: present
      when: ansible_distribution not in ['CentOS', 'Red Hat Enterprise Linux', 'Fedora']
